### ISSUE TITLE
Rewrite redux-sauce to Redux Toolkit

### ISSUE THREAD

**Issue by novellizator** [salsita/react-training#26]
Since we [agreed](https://www.notion.so/salsita/2020-07-03-Training-Crew-Sync-afd46e512bd54dcbb3ab8d7f6537fedc) that [redux toolkit](https://redux-toolkit.js.org/) is our official way to write redux actions, we need to update the training materials.

This will include:

1. Rewrite of the solution for the redux sauce exercise
2. Update the solution in _all_ consecutive exercises
3. Update [Tutorial](https://github.com/salsita/react-training/blob/master/README.md)
4. Update Slides in the presentation

Please check the linked pull request with the skeleton of the change (only step 1 was done)

**Comment by dinassh** [comment]
Closing in favor of rewriting exercises one by one.
