### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by novellizator** [salsita/react-training#31]
Code formatting standards are always good to have.

Here follows an excerpt of package.json of other projects (taken by Karel Klima), this issue should implement this.

```
{
  "eslintConfig": {
    "extends": "react-app/recommended",
    "rules": {
      "quotes": [
        "error",
        "single"
      ],
      "semi": [
        "error",
        "never"
      ]
    }
  },
  "prettier": {
    "singleQuote": true,
    "semi": false,
    "endOfLine": "auto"
  },

```

**Comment by dinassh** [comment]
@novellizator 

1. The eslint is not configured for this project. Would the 'prettier' alone suffice here or do you wish to configure the eslint as well?
2. Applying the provided settings results in a large number of changes:
    `
    115 files changed, 1278 insertions(+), 1179 deletions(-)
    `
    It seems to me, that different style guide was used on this project. The number of changes may be reduced greatly when using the following rules:
    ```json
    {
      "singleQuote": true,
      "semi": true,
      "endOfLine": "auto",
      "trailingComma": "none",
      "arrowParens": "avoid"
    }
    ```
    Resulting in  `51 files changed, 314 insertions(+), 221 deletions(-)`.

    I would prefer to apply rules which result in smaller number of changes. Is the provided example mandatory? How shall I proceed in your opinion?

**Comment by dinassh** [comment]
Closing. Resolved in https://github.com/salsita/react-training/issues/36
