### ISSUE TITLE
React.FC usage

### ISSUE THREAD

**Issue by dinassh** [salsita/react-training#61]
The discussion about usage of `React.FC` for typing of components was reopened

See 
- https://github.com/salsita/react-training/pull/53#discussion_r467910804
- https://github.com/facebook/create-react-app/pull/8177 (same link as in the discussion)

**Comment by novellizator** [comment]
I personally don't find any of the downsides particularly itchy (at least in the scope of the trainings), but if someone is strongly against React.FC, I'm fine it being removed.
